# Generated by Django 5.2.8 on 2026-02-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('info', 'معلومة'), ('warning', 'تحذير'), ('medical', 'طبي'), ('critical', 'حرج')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'مجدول'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='donormedicalprofile',
            name='organ_available',
            field=models.CharField(choices=[('kidney', 'كلية'), ('liver', 'كبد'), ('heart', 'قلب'), ('lung', 'رئة'), ('pancreas', 'بنكرياس')], default='Kindy', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_type',
            field=models.CharField(choices=[('public', 'حكومي'), ('private', 'خاص')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='organmatching',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('matched', 'مطابق'), ('rejected', 'مرفوض')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientmedicalprofile',
            name='organ_needed',
            field=models.CharField(choices=[('kidney', 'كلية'), ('liver', 'كبد'), ('heart', 'قلب'), ('lung', 'رئة'), ('pancreas', 'بنكرياس')], default='Kindy', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientpriority',
            name='level',
            field=models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'مرتفع'), ('critical', 'حرج')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر '), ('female', 'انثي')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('donor', 'Donor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('under_review', 'قيد المراجعة'), ('rejected', 'مرفوض')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userchronicdisease',
            name='severity',
            field=models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي')], max_length=20),
        ),
    ]
